# Build stage
FROM gradle:8.5-jdk21 AS builder
WORKDIR /app

# Copia tudo, exceto o que estiver no .dockerignore
COPY . .

RUN ./gradlew :infrastructure:build -x test --no-daemon

# Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/infrastructure/build/libs/infrastructure-*.jar app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java", "-jar", "app.jar"]
