version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_NAME: debugattor
      DB_USERNAME: debugattor
      DB_PASSWORD: debugattor
      FLYWAY_ENABLED: true
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: debugattor
      POSTGRES_USER: debugattor
      POSTGRES_PASSWORD: debugattor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U debugattor"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  db_data:
